apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: baremetal-clusterclass-v0.1.0-control-plane
spec:
  template:
    spec:
      version: ""
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              authorization-mode: "Node,RBAC"
            timeoutForControlPlane: 10m
          etcd:
            local:
              dataDir: /var/lib/etcd
        initConfiguration:
          nodeRegistration:
            kubelet:
              extraArgs:
                max-pods: "250"
