apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: baremetal-kubeadm-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
            - name: authorization-mode
              value: "Node,RBAC"
          etcd:
            local:
              dataDir: /var/lib/etcd
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
            - name: max-pods
              value: "250"
      rollout:
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
