apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: baremetal-clusterclass-v0.1.0-default-worker
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubelet:
            extraArgs:
              max-pods: "250"
