apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cvo-manager-role
rules:
- apiGroups:
  - cvo.capbm.io
  resources:
  - clusterversions
  - clusterversions/status
  - clusterversions/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvo.capbm.io
  resources:
  - releaseimages
  - releaseimages/status
  - releaseimages/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvo.capbm.io
  resources:
  - upgradepaths
  - upgradepaths/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvo.capbm.io
  resources:
  - releasecatalogs
  - releasecatalogs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvo.capbm.io
  resources:
  - clusteraddons
  - clusteraddons/status
  - clusteraddons/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
