apiVersion: apps/v1
kind: Deployment
metadata:
  name: capbm-controller-manager
  namespace: capbm-system
  labels:
    control-plane: capbm-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: capbm-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: capbm-controller-manager
    spec:
      serviceAccountName: capbm-controller-manager
      containers:
      - name: manager
        image: ghcr.io/betawater/capbm-manager:latest
        command:
        - /capbm-manager
        args:
        - --leader-elect
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
