apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/cvo.capbm.io_clusterversions.yaml
- bases/cvo.capbm.io_releaseimages.yaml
- bases/cvo.capbm.io_upgradepaths.yaml
- bases/cvo.capbm.io_releasecatalogs.yaml
- bases/cvo.capbm.io_clusteraddons.yaml
