apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- baremetal-clusterclass.yaml
- baremetal-cluster-template.yaml
- baremetal-machine-template-cp.yaml
- baremetal-machine-template-worker.yaml
- kubeadm-controlplane-template.yaml
- kubeadm-config-template.yaml
